services:
  ai-alfresco-share:
    image: alfresco-share-ai-alfresco:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../ai-alfresco-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: ai-alfresco-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  ai-alfresco-acs:
    image: alfresco-content-services-ai-alfresco:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../ai-alfresco-platform-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: '
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dtransform.service.enabled=true
        -Dlocal.transform.service.enabled=true
        -DlocalTransform.core-aio.url=http://ai-alfresco-transform-core-aio:8090/
        -Dmessaging.broker.url="failover:(nio://ai-alfresco-activemq:61616)?timeout=3000&jms.useCompression=true"
        -Daws.key=
        -Daws.secret=
        '
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - ai-alfresco-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - ai-alfresco-postgres
  ai-alfresco-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - ai-alfresco-db-volume:/var/lib/postgresql/data
  ai-alfresco-ass:
    image: alfresco/alfresco-search-services:2.0.3
    environment:
      SOLR_ALFRESCO_HOST: ai-alfresco-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: ai-alfresco-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
    ports:
      - "8983:8983"
    volumes:
      - ai-alfresco-ass-volume:/opt/alfresco-search-services/contentstore
      - ai-alfresco-ass-volume:/opt/alfresco-search-services/data
  ai-alfresco-transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:5.1.0
    mem_limit: 1536m
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
    ports:
      - 8090:8090
  ai-alfresco-activemq:
    image: alfresco/alfresco-activemq:5.16.1
    mem_limit: 1g
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP

volumes:
  ai-alfresco-acs-volume:
    external: true
  ai-alfresco-db-volume:
    external: true
  ai-alfresco-ass-volume:
    external: true
