# This file should contain content model labels

# Ticket Metadata
ai_contentModel.ai_tickets.title=Ticket Metadata
ai_contentModel.aspect.ai_tickets.title=Ticket Metadata
ai_contentModel.property.ai_ticketDate.title=Date
ai_contentModel.property.ai_ticketTax.title=Tax
ai_contentModel.property.ai_ticketTotal.title=Total
ai_contentModel.property.ai_ticketCountry.title=Country

# Invoice Metadata
ai_contentModel.ai_invoices.title=Invoice Metadata
ai_contentModel.aspect.ai_invoices.title=Invoice Metadata
ai_contentModel.property.ai_invoiceDate.title=Date
ai_contentModel.property.ai_invoiceNumber.title=Nº Invoice
ai_contentModel.property.ai_invoiceTotal.title=Total Invoice
ai_contentModel.property.ai_invoiceTax.title=Tax